### ISSUE TITLE
感谢作者！同时提几个小建议~

### ISSUE THREAD

**Issue by holwell** [Mz1z/HLSdownload#1]
第一，执行过程中无法终止，应该是子线程daemon设置的问题。
第二，建议加入一个参数，即时间间隔参数，即每当m4s视频的时间长度达到多少，保存为一个单独的文件，并将后续数据写入新的文件中，方便边录制边转码处理等。

**Comment by Mz1z** [comment]
建议很好，如果能提个PR就更好了

**Comment by Mz1z** [comment]
> 第一，执行过程中无法终止，应该是子线程daemon设置的问题。 第二，建议加入一个参数，即时间间隔参数，即每当m4s视频的时间长度达到多少，保存为一个单独的文件，并将后续数据写入新的文件中，方便边录制边转码处理等。

建议很好，如果能提个PR就更好了
